package seeder

import (
	"backend/internal/core/domain"
	"fmt"
	"gorm.io/gorm"
)

func SeedNewsAnimes(db *gorm.DB) {
	animes := []struct {
		anime   domain.Anime
		epCount int
		cats    []string
		year    int
	}{
		// 1. Solo Leveling
		{
			anime: domain.Anime{
				Title:       "Solo Leveling سولو ليفيلينغ",
				TitleEn:     "Solo Leveling",
				Slug:        "solo-leveling",
				SlugEn:      "solo-leveling",
				Description: "في عالم يظهر فيه 'البوابات' التي تربط عالمنا بأبعاد أخرى، يكتسب البعض قوى خارقة ليصبحوا 'صيادين'. سونغ جين وو هو أضعف صياد على الإطلاق، لكن بعد حادثة غامضة في دجن مزدوج، يكتسب نظاماً فريداً يتيح له رفع مستواه والقوة بشكل لا نهائي.",
				DescriptionEn: "In a world where 'Gates' appear, connecting our world to other dimensions, some people gain superpowers to become 'Hunters'. Sung Jin-woo is the weakest hunter of all, but after a mysterious incident in a Double Dungeon, he gains a unique system that allowed him to level up and gain infinite strength.",
				Seasons:     1,
				Status:      "Running",
				Rating:      8.7,
				Image:       "/uploads/animes/solo-leveling.png",
				Cover:       "/uploads/animes/solo-leveling.png",
				StudioName:  "A-1 Pictures",
				Duration:    24,
				Language:    "Japan",
				Type:        "TV",
				IsPublished: false,
			},
			epCount: 12,
			cats:    []string{"action", "adventure", "fantasy"},
			year:    2024,
		},
		// 2. Fist of the North Star
		{
			anime: domain.Anime{
				Title:       "Fist of the North Star سيف النار",
				TitleEn:     "Fist of the North Star",
				Slug:        "fist-of-the-north-star",
				SlugEn:      "fist-of-the-north-star",
				Description: "بعد حرب نووية دمرت الحضارة، يعيش الناجون في عالم فوضوي يحكمه القوي. كينشيرو، وريث فن القتال القاتل 'هوكوتو شينكين'، يسافر عبر القفار لحماية الأبرياء والبحث عن خطيبته المختطفة يوريا، مواجهاً خصوماً أقوياء بضربات قاتلة من الداخل.",
				DescriptionEn: "After a nuclear war destroyed civilization, survivors live in a chaotic world ruled by the strong. Kenshiro, the successor of the deadly martial art 'Hokuto Shinken', travels through the wasteland to protect the innocent and search for his kidnapped fiancée Yuria, facing powerful opponents with deadly internal strikes.",
				Seasons:     1,
				Status:      "Completed",
				Rating:      8.2,
				Image:       "/uploads/animes/fist-of-the-north-star.png",
				Cover:       "/uploads/animes/fist-of-the-north-star.png",
				StudioName:  "Toei Animation",
				Duration:    24,
				Language:    "Japan",
				Type:        "TV",
				IsPublished: false,
			},
			epCount: 109,
			cats:    []string{"action", "drama", "sci-fi"},
			year:    1984,
		},
		// 3. Megalobox
		{
			anime: domain.Anime{
				Title:       "Megalobox ميغالو بوكس",
				TitleEn:     "Megalobox",
				Slug:        "megalobox",
				SlugEn:      "megalobox",
				Description: "في مستقبل بائس، تعتبر رياضة 'ميغالو بوكس' (ملاكمة معززة تقنياً) قمة الإثارة. 'جونك دوغ' ملاكم مجهول يقاتل في الحلبات السرية، يقرر المشاركة في البطولة الكبرى 'ميغالونيا' بدون أي معدات تقنية، متحدياً المستحيل باسم 'جو بلا تروس'.",
				DescriptionEn: "In a box future, 'Megalobox' (technologically enhanced boxing) is the ultimate thrill. 'Junk Dog', an anonymous boxer fighting in underground rings, decides to participate in the major tournament 'Megalonia' without any mechanical gear, challenging the impossible as 'Gearless Joe'.",
				Seasons:     2,
				Status:      "Completed",
				Rating:      8.1,
				Image:       "/uploads/animes/megalobox.jpg",
				Cover:       "/uploads/animes/megalobox.jpg",
				StudioName:  "TMS Entertainment",
				Duration:    24,
				Language:    "Japan",
				Type:        "TV",
				IsPublished: false,
			},
			epCount: 13,
			cats:    []string{"action", "drama", "sports", "sci-fi"},
			year:    2018,
		},
		// 4. Kaiju No. 8
		{
			anime: domain.Anime{
				Title:       "Kaiju No. 8 كايجو رقم 8",
				TitleEn:     "Kaiju No. 8",
				Slug:        "kaiju-no-8",
				SlugEn:      "kaiju-no-8",
				Description: "في يابان تتعرض لهجمات مستمرة من الوحوش العملاقة 'كايجو'، يحلم كافكا هيبينو بالانضمام لقوات الدفاع. بعد سنوات من فشله واكتفائه بتنظيف جثث الوحوش، يبتلع كافكا وحشاً صغيراً يمنحه القدرة على التحول لـ 'كايجو' بشري، ليصبح التهديد الأكبر والمنقذ في آن واحد.",
				DescriptionEn: "In a Japan suffering from constant attacks by giant monsters 'Kaiju', Kafka Hibino dreams of joining the Defense Force. After years of failure and settling for cleaning up monster corpses, Kafka swallows a small monster that gives him the ability to transform into a humanoid 'Kaiju', becoming the ultimate threat and savior at the same time.",
				Seasons:     1,
				Status:      "Running",
				Rating:      8.5,
				Image:       "/uploads/animes/kaiju-no-8.png",
				Cover:       "/uploads/animes/kaiju-no-8.png",
				StudioName:  "Production I.G",
				Duration:    24,
				Language:    "Japan",
				Type:        "TV",
				IsPublished: false,
			},
			epCount: 12,
			cats:    []string{"action", "sci-fi", "shounen"},
			year:    2024,
		},
		// 5. Kaguya-sama: Love is War
		{
			anime: domain.Anime{
				Title:       "Kaguya-sama: Love is War كاغويا ساما: الحب حرب",
				TitleEn:     "Kaguya-sama: Love is War",
				Slug:        "kaguya-sama-love-is-war",
				SlugEn:      "kaguya-sama-love-is-war",
				Description: "في أكاديمية شوتشين، يقع رئيس مجلس الطلبة ميوكي شيروجاني ونائبته كاغويا شينوميا في حب بعضهما. لكن، بسبب كبريائهما العالي، يعتبران أول من يعترف بمشاعره هو الخاسر. هكذا تبدأ حرب نفسية كوميدية لإجبار الطرف الآخر على الاعتراف أولاً.",
				DescriptionEn: "At Shuchiin Academy, Student Council President Miyuki Shirogane and Vice President Kaguya Shinomiya fall in love with each other. However, due to their high pride, they consider the first person to confess their feelings to be the loser. Thus begins a psychological comedy war to force the other party to confess first.",
				Seasons:     3,
				Status:      "Completed",
				Rating:      8.9,
				Image:       "/uploads/animes/kaguya-sama-love-is-war.jpg",
				Cover:       "/uploads/animes/kaguya-sama-love-is-war.jpg",
				StudioName:  "A-1 Pictures",
				Duration:    24,
				Language:    "Japan",
				Type:        "TV",
				IsPublished: false,
			},
			epCount: 12,
			cats:    []string{"comedy", "romance", "slice-of-life"},
			year:    2019,
		},
		// 6. Tojima Wants to be a Kamen Rider
		{
			anime: domain.Anime{
				Title:       "Tojima Wants to be a Kamen Rider توجيما يريد أن يصبح كامن رايدر",
				TitleEn:     "Tojima Wants to be a Kamen Rider",
				Slug:        "tojima-wants-to-be-a-kamen-rider",
				SlugEn:      "tojima-wants-to-be-a-kamen-rider",
				Description: "قصة كوميدية فريدة حول توجيما، الشاب المهووس بسلسلة 'كامن رايدر'، الذي يسعى جاهداً لتحويل حياته اليومية إلى مغامرة بطولية تشبه مسلسله المفضل، مواجهاً مواقف مضحكة ومحرجة في محاولته للتحول إلى بطل خارق في الواقع.",
				DescriptionEn: "A unique comedy story about Tojima, a young man obsessed with the 'Kamen Rider' series, who strives to turn his daily life into a heroic adventure similar to his favorite show, facing funny and embarrassing situations in his attempt to transform into a real-life superhero.",
				Seasons:     1,
				Status:      "Running",
				Rating:      7.5,
				Image:       "/uploads/animes/tojima-wants-to-be-a-kamen-rider.png",
				Cover:       "/uploads/animes/tojima-wants-to-be-a-kamen-rider.png",
				StudioName:  "Original",
				Duration:    15,
				Language:    "Japan",
				Type:        "ONA",
				IsPublished: false,
			},
			epCount: 10,
			cats:    []string{"comedy", "slice-of-life", "parody"},
			year:    2024,
		},
		// 7. One Punch Man
		{
			anime: domain.Anime{
				Title:       "One Punch Man ون بانش مان",
				TitleEn:     "One Punch Man",
				Slug:        "one-punch-man-news",
				SlugEn:      "one-punch-man",
				Description: "سايتاما هو بطل خارق أصبح قوياً لدرجة أنه يهزم أي عدو بلكمة واحدة فقط. هذا يسبب له مللاً كبيراً وإحباطاً لأنه لم يعد يجد متعة في القتال، بينما يستمر في حماية الأرض من التهديدات المتزايدة رفقة تلميذه السايبورغ جينوس.",
				DescriptionEn: "Saitama is a superhero who has become so strong that he defeats any enemy with just a single punch. This causes him great boredom and frustration as he no longer finds joy in fighting, while he continues to protect Earth from increasing threats alongside his cyborg disciple Genos.",
				Seasons:     2,
				Status:      "Running",
				Rating:      8.7,
				Image:       "/uploads/animes/one-punch-man.png",
				Cover:       "/uploads/animes/one-punch-man.png",
				StudioName:  "Madhouse",
				Duration:    24,
				Language:    "Japan",
				Type:        "TV",
				IsPublished: false,
			},
			epCount: 12,
			cats:    []string{"action", "comedy", "supernatural"},
			year:    2015,
		},
		// 8. The Outcast 6
		{
			anime: domain.Anime{
				Title:       "The Outcast 6 المنبوذ 6",
				TitleEn:     "The Outcast 6",
				Slug:        "the-outcast-6",
				SlugEn:      "the-outcast-6",
				Description: "في الموسم السادس من 'Hitori no Shita'، تستمر رحلة تشو سوران وفوفو في البحث عن أسرار الماضي وقوى 'الطريق المثمن'. تواجه الشخصيات تحديات جديدة من منظمات سرية تسعى للسيطرة على القوى الروحية القديمة وسط صراعات ملحمية.",
				DescriptionEn: "In the sixth season of 'Hitori no Shita', Cho Soran and Fufuu's journey continues as they search for secrets of the past and the 'Eight Great Arts'. Characters face new challenges from secret organizations seeking to control ancient spiritual powers amidst epic conflicts.",
				Seasons:     6,
				Status:      "Running",
				Rating:      8.0,
				Image:       "/uploads/animes/the-outcast-6.png",
				Cover:       "/uploads/animes/the-outcast-6.png",
				StudioName:  "Tencent Animation",
				Duration:    20,
				Language:    "China",
				Type:        "ONA",
				IsPublished: false,
			},
			epCount: 12,
			cats:    []string{"action", "supernatural", "martial-arts"},
			year:    2024,
		},
		// 9. Failure Frame
		{
			anime: domain.Anime{
				Title:       "Failure Frame إطار الفشل: أصبحت الأقوى وأبدت كل شيء بسحر منخفض المستوى",
				TitleEn:     "Failure Frame: I Became the Strongest and Annihilated Everything with Low-Level Spells",
				Slug:        "failure-frame",
				SlugEn:      "failure-frame",
				Description: "تم استدعاء توكا ميموري وزملاؤه إلى عالم آخر كأبطال. لكن توكا حصل على أقل رتبة (E) وتم التخلي عنه في دجن مميت من قبل الإلهة. هناك، يكتشف أن مهاراته التي تعتبر 'فاشلة' هي في الواقع مرعبة وقاتلة، ليبدأ رحلة الانتقام.",
				DescriptionEn: "Touka Mimori and his classmates are summoned to another world as heroes. However, Touka receives the lowest rank (E) and is abandoned in a deadly dungeon by the Goddess. There, he discovers that his skills considered 'failed' are actually terrifying and lethal, beginning a journey of revenge.",
				Seasons:     1,
				Status:      "Running",
				Rating:      7.2,
				Image:       "/uploads/animes/failure-frame.jpg",
				Cover:       "/uploads/animes/failure-frame.jpg",
				StudioName:  "Seven Arcs",
				Duration:    24,
				Language:    "Japan",
				Type:        "TV",
				IsPublished: false,
			},
			epCount: 12,
			cats:    []string{"action", "adventure", "fantasy", "isekai"},
			year:    2024,
		},
		// 10. Tokyo Revengers
		{
			anime: domain.Anime{
				Title:       "Tokyo Revengers طوكيو ريفينجرز",
				TitleEn:     "Tokyo Revengers",
				Slug:        "tokyo-revengers-news",
				SlugEn:      "tokyo-revengers",
				Description: "تاكيميتشي هاناجاكي، شاب يعيش حياة بائسة، يكتشف أن صديقته السابقة قتلت على يد عصابة طوكيو مانجي. بعد حادث غامض، يعود بالزمن 12 عاماً إلى الوراء، ليقرر التسلل إلى العصابة وتغيير المستقبل لإنقاذ حياة هيناتا والآخرين.",
				DescriptionEn: "Takemichi Hanagaki, a leading a miserable life, discovers that his former girlfriend was killed by the Tokyo Manji Gang. After a mysterious accident, he travels back 12 years in time, deciding to infiltrate the gang and change the future to save Hinata's life and others.",
				Seasons:     3,
				Status:      "Running",
				Rating:      8.1,
				Image:       "/uploads/animes/tokyo-revengers.jpg",
				Cover:       "/uploads/animes/tokyo-revengers.jpg",
				StudioName:  "LidenFilms",
				Duration:    24,
				Language:    "Japan",
				Type:        "TV",
				IsPublished: false,
			},
			epCount: 12,
			cats:    []string{"action", "drama", "supernatural", "shounen"},
			year:    2021,
		},
		// 11. Dead Account
		{
			anime: domain.Anime{
				Title:       "Dead Account الحساب الميت",
				TitleEn:     "Dead Account",
				Slug:        "dead-account",
				SlugEn:      "dead-account",
				Description: "في عصر السوشيال ميديا، تبدأ ظواهر غريبة بالظهور مرتبطة بحسابات المتوفين. يجد بطل القصة نفسه متورطاً في عالم 'الأرواح الرقمية' حيث يجب عليه استخدام مهاراته التقنية والروحية لمواجهة كيانات خبيثة تهدد العالمين الحقيقي والرقمي.",
				DescriptionEn: "In the age of social media, strange phenomena begin to appear linked to the accounts of the deceased. The protagonist finds himself involved in a world of 'Digital Souls' where he must use his technical and spiritual skills to face malicious entities threatening both the real and digital worlds.",
				Seasons:     1,
				Status:      "Running",
				Rating:      7.8,
				Image:       "/uploads/animes/dead-account.png",
				Cover:       "/uploads/animes/dead-account.png",
				StudioName:  "Kodansha",
				Duration:    24,
				Language:    "Japan",
				Type:        "TV",
				IsPublished: false,
			},
			epCount: 12,
			cats:    []string{"action", "supernatural", "mystery"},
			year:    2024,
		},
		// 12. Wind Breaker Season 2
		{
			anime: domain.Anime{
				Title:       "Wind Breaker Season 2 ويند بريكر - الموسم الثاني",
				TitleEn:     "Wind Breaker Season 2",
				Slug:        "wind-breaker-season-2",
				SlugEn:      "wind-breaker-season-2",
				Description: "يستمر ساكورا هاروكا وزملاؤه في ثانوية 'فورين' في حماية مدينتهم كأبطال محليين. في هذا الموسم، تظهر تحديات جديدة وعصابات منافسة تهدد السلام الذي يدافعون عنه، بينما تزداد قوة الروابط بين أعضاء الفريق.",
				DescriptionEn: "Sakura Haruka and his classmates at 'Furin' High School continue to protect their city as local heroes. This season, new challenges and rival gangs emerge threatening the peace they defend, while the bonds between team members grow stronger.",
				Seasons:     2,
				Status:      "Upcoming",
				Rating:      8.3,
				Image:       "/uploads/animes/wind-breaker-season-2.jpg",
				Cover:       "/uploads/animes/wind-breaker-season-2.jpg",
				StudioName:  "CloverWorks",
				Duration:    24,
				Language:    "Japan",
				Type:        "TV",
				IsPublished: false,
			},
			epCount: 12,
			cats:    []string{"action", "drama", "shounen"},
			year:    2025,
		},
		// 13. Solo Camping for Two
		{
			anime: domain.Anime{
				Title:       "Solo Camping for Two تخييم انفرادي لشخصين",
				TitleEn:     "Solo Camping for Two",
				Slug:        "solo-camping-for-two",
				SlugEn:      "solo-camping-for-two",
				Description: "قصة مريحة وهادئة حول شخصين يعشقان التخييم الانفرادي، لكن الظروف تضعهما دائماً في نفس الموقع. تبدأ علاقة فريدة بينهما تقوم على مشاركة الوجبات والهدوء في الطبيعة، مع الحفاظ على مساحتهما الخاصة.",
				DescriptionEn: "A relaxing and calm story about two people who love solo camping, but circumstances always put them in the same location. A unique relationship begins between them based on sharing meals and quietness in nature, while maintaining their private space.",
				Seasons:     1,
				Status:      "Running",
				Rating:      7.4,
				Image:       "/uploads/animes/solo-camping-for-two.png",
				Cover:       "/uploads/animes/solo-camping-for-two.png",
				StudioName:  "Original",
				Duration:    24,
				Language:    "Japan",
				Type:        "TV",
				IsPublished: false,
			},
			epCount: 12,
			cats:    []string{"slice-of-life", "comedy"},
			year:    2024,
		},
		// 14. Gachiakuta
		{
			anime: domain.Anime{
				Title:       "Gachiakuta غاتشياكوتا",
				TitleEn:     "Gachiakuta",
				Slug:        "gachiakuta",
				SlugEn:      "gachiakuta",
				Description: "في عالم مقسم بين ساكني السماء ومن يعيشون في القاع وسط القمامة، يُتهم الشاب لودو بجريمة لم يرتكبها ويُلقى به في 'الهاوية'. هناك، يكتشف قوة فريدة تتيح له تحويل القمامة إلى أسلحة قوية، ويبدأ رحلة للتمرد ضد النظام الظالم.",
				DescriptionEn: "In a world divided between sky-dwellers and those living in the bottom amidst garbage, the young Rudo is accused of a crime he didn't commit and thrown into the 'Abyss'. There, he discovers a unique power allowing him to turn trash into powerful weapons, beginning a journey to rebel against the unjust system.",
				Seasons:     1,
				Status:      "Upcoming",
				Rating:      8.4,
				Image:       "/uploads/animes/gachiakuta.png",
				Cover:       "/uploads/animes/gachiakuta.png",
				StudioName:  "Bones",
				Duration:    24,
				Language:    "Japan",
				Type:        "TV",
				IsPublished: false,
			},
			epCount: 12,
			cats:    []string{"action", "adventure", "dark-fantasy", "shounen"},
			year:    2025,
		},
		// 15. Tougen Anki
		{
			anime: domain.Anime{
				Title:       "Tougen Anki توجين أنكي",
				TitleEn:     "Tougen Anki",
				Slug:        "tougen-anki",
				SlugEn:      "tougen-anki",
				Description: "في عالم توجد فيه سلالات الـ 'أوني' والـ 'موموتارو' في صراع دائم، يكتشف شيكي إيتشينوسي فجأة أنه يحمل دم الـ 'أوني'. بعد هجوم مباغت يدمر حياته الهادئة، يقرر الانضمام لأكاديمية الـ 'أوني' ليتعلم السيطرة على قواه والانتقام لعائلته.",
				DescriptionEn: "In a world where the 'Oni' and 'Momotaro' lineages are in constant conflict, Shiki Ichinose suddenly discovers he carries 'Oni' blood. After a surprise attack destroys his peaceful life, he decides to join the 'Oni' academy to learn to control his powers and avenge his family.",
				Seasons:     1,
				Status:      "Upcoming",
				Rating:      7.9,
				Image:       "/uploads/animes/tougen-anki.png",
				Cover:       "/uploads/animes/tougen-anki.png",
				StudioName:  "Original",
				Duration:    24,
				Language:    "Japan",
				Type:        "TV",
				IsPublished: false,
			},
			epCount: 12,
			cats:    []string{"action", "fantasy", "shounen"},
			year:    2025,
		},
		// 16. Demon Slayer: Infinity Castle
		{
			anime: domain.Anime{
				Title:       "Demon Slayer: Kimetsu no Yaiba – Infinity Castle قاتل الشياطين: قلعة اللانهاية",
				TitleEn:     "Demon Slayer: Kimetsu no Yaiba – Infinity Castle",
				Slug:        "demon-slayer-infinity-castle",
				SlugEn:      "demon-slayer-infinity-castle",
				Description: "تبدأ المعركة الختامية داخل قلعة اللانهاية التابعة لموزان. يواجه الهاشيرا وتانجيرو رفاقه أقوى شياطين الأقمار العليا في مواجهات ملحمية ومميتة، حيث يتم اختبار مهاراتهم وقوة إرادتهم في إنهاء عهد الشياطين مرة وإلى الأبد.",
				DescriptionEn: "The final battle begins inside Muzan's Infinity Castle. The Hashira and Tanjiro with his companions face the strongest Upper Moon demons in epic and deadly confrontations, testing their skills and willpower to end the era of demons once and for all.",
				Seasons:     4,
				Status:      "Upcoming",
				Rating:      9.3,
				Image:       "/uploads/animes/demon-slayer-infinity-castle.jpg",
				Cover:       "/uploads/animes/demon-slayer-infinity-castle.jpg",
				StudioName:  "ufotable",
				Duration:    120,
				Language:    "Japan",
				Type:        "Movie",
				IsPublished: false,
			},
			epCount: 3,
			cats:    []string{"action", "fantasy", "shounen"},
			year:    2025,
		},
		// 17. My Hero Academia
		{
			anime: domain.Anime{
				Title:       "My Hero Academia أكاديميتي للأبطال",
				TitleEn:     "My Hero Academia",
				Slug:        "my-hero-academia-news",
				SlugEn:      "my-hero-academia",
				Description: "في عالم يمتلك فيه معظم الناس قوى خارقة تسمى 'ميزات'، يولد إيزوكو ميدوريا بدون أي قوى ولكنه يحلم بأن يصبح بطلاً. بعد لقاء مصيري مع البطل الأول 'أول مايت'، يحصل على قوة 'الواحد للكل' ويبدأ رحلته في مدرسة UA للأبطال.",
				DescriptionEn: "In a world where most people possess superpowers called 'Quirks', Izuku Midoriya is born without any powers but dreams of becoming a hero. After a fateful encounter with the Number One Hero 'All Might', he receives the power 'One For All' and begins his journey at UA High School.",
				Seasons:     7,
				Status:      "Running",
				Rating:      8.5,
				Image:       "/uploads/animes/my-hero-academia.png",
				Cover:       "/uploads/animes/my-hero-academia.png",
				StudioName:  "Bones",
				Duration:    24,
				Language:    "Japan",
				Type:        "TV",
				IsPublished: false,
			},
			epCount: 25,
			cats:    []string{"action", "superhero", "shounen"},
			year:    2016,
		},
		// 18. Fire Force Season 3
		{
			anime: domain.Anime{
				Title:       "Fire Force Season 3 قوة النار - الموسم الثالث",
				TitleEn:     "Fire Force Season 3",
				Slug:        "fire-force-season-3",
				SlugEn:      "fire-force-season-3",
				Description: "يستمر شينرا كوساكابي وفريقه في وحدة الإطفاء الخاصة الثامنة في كشف أسرار كوارث 'الاحتراق البشري'. في هذا الموسم، تشتعل المعارك ضد 'المبشر' وأتباعه مع اقتراب الكارثة الكبرى وتطور قدرات شينرا الروحية والنارية.",
				DescriptionEn: "Shinra Kusakabe and his team in the Special Fire Force Company 8 continue to uncover the secrets of the 'Human Combustion' disasters. This season, battles ignite against 'The Evangelist' and his followers as the Great Cataclysm approaches and Shinra's spiritual and fiery abilities evolve.",
				Seasons:     3,
				Status:      "Upcoming",
				Rating:      8.4,
				Image:       "/uploads/animes/fire-force-season-3.png",
				Cover:       "/uploads/animes/fire-force-season-3.png",
				StudioName:  "David Production",
				Duration:    24,
				Language:    "Japan",
				Type:        "TV",
				IsPublished: false,
			},
			epCount: 24,
			cats:    []string{"action", "supernatural", "shounen"},
			year:    2025,
		},
		// 19. 86 Eighty-Six
		{
			anime: domain.Anime{
				Title:       "86 Eighty-Six 86",
				TitleEn:     "86 Eighty-Six",
				Slug:        "86-eighty-six",
				SlugEn:      "86-eighty-six",
				Description: "تدعي جمهورية سان مانوليا أنها لا تقدم أي خسائر بشرية في حربها ضد 'الفيلق'. لكن الحقيقة هي أن هناك منطقة سرية (86) حيث يُجبر المضطهدون على قيادة الآلات القتالية والموت بصمت. تبدأ الملازم لينا بقيادة فرقة 'سبيرهيد' وتكتشف قسوة الواقع.",
				DescriptionEn: "The Republic of San Magnolia claims to suffer no human casualties in its war against the 'Legion'. But the truth is there is a secret sector (86) where the oppressed are forced to pilot combat machines and die in silence. Lieutenant Lena begins commanding the 'Spearhead' squadron and discovers the harsh reality.",
				Seasons:     2,
				Status:      "Completed",
				Rating:      8.7,
				Image:       "/uploads/animes/86-eighty-six.jpg",
				Cover:       "/uploads/animes/86-eighty-six.jpg",
				StudioName:  "A-1 Pictures",
				Duration:    24,
				Language:    "Japan",
				Type:        "TV",
				IsPublished: false,
			},
			epCount: 23,
			cats:    []string{"action", "drama", "sci-fi", "military"},
			year:    2021,
		},
		// 20. Hell's Paradise
		{
			anime: domain.Anime{
				Title:       "Hell's Paradise جنة الجحيم",
				TitleEn:     "Hell's Paradise",
				Slug:        "hells-paradise",
				SlugEn:      "hells-paradise",
				Description: "يُحكم على النينجا القاتل غابيمارو بالإعدام، لكن يتم منحه فرصة أخيرة: الذهاب إلى جزيرة غامضة وملعونة لإحضار 'إكسير الحياة'. يرافقه الجلادة ساغيري، ليجدا نفسيهما في مواجهة مخلوقات مرعبة ومنافسين خطرين في صراع من أجل البقاء.",
				DescriptionEn: "The deadly ninja Gabimaru is sentenced to death, but given one last chance: travel to a mysterious and cursed island to retrieve the 'Elixir of Life'. Accompanied by the executioner Sagiri, they find themselves facing terrifying creatures and dangerous rivals in a struggle for survival.",
				Seasons:     1,
				Status:      "Running",
				Rating:      8.3,
				Image:       "/uploads/animes/hells-paradise.png",
				Cover:       "/uploads/animes/hells-paradise.png",
				StudioName:  "MAPPA",
				Duration:    24,
				Language:    "Japan",
				Type:        "TV",
				IsPublished: false,
			},
			epCount: 13,
			cats:    []string{"action", "adventure", "fantasy", "shounen"},
			year:    2023,
		},
		// 22. Detective Conan
		{
			anime: domain.Anime{
				Title:       "Detective Conan المحقق كونان",
				TitleEn:     "Detective Conan",
				Slug:        "detective-conan-news",
				SlugEn:      "detective-conan",
				Description: "سينشي كودو هو محقق مراهق عبقري يتقلص جسده ليصبح طفلاً بعد أن أجبره أعضاء من 'المنظمة السوداء' على تناول عقار تجريبي. باستخدام هويته الجديدة 'كونان إيدوجاوا'، يبدأ بحل القضايا المعقدة سراً بينما يبحث عن وسيلة لاستعادة جسده.",
				DescriptionEn: "Shinichi Kudo is a genius teenage detective whose body shrinks into a child's after members of the 'Black Organization' force him to consume an experimental drug. Using his new identity 'Conan Edogawa', he begins solving complex cases secretly while searching for a way to restore his body.",
				Seasons:     1,
				Status:      "Running",
				Rating:      8.5,
				Image:       "/uploads/animes/detective-conan.jpg",
				Cover:       "/uploads/animes/detective-conan.jpg",
				StudioName:  "TMS Entertainment",
				Duration:    24,
				Language:    "Japan",
				Type:        "TV",
				IsPublished: false,
			},
			epCount: 1100,
			cats:    []string{"mystery", "adventure", "police"},
			year:    1996,
		},
		// 23. Dr. Stone
		{
			anime: domain.Anime{
				Title:       "Dr. Stone دكتور ستون",
				TitleEn:     "Dr. Stone",
				Slug:        "dr-stone",
				SlugEn:      "dr-stone",
				Description: "فجأة، يتحول كل البشر إلى حجارة. بعد آلاف السنين، يستيقظ عبقري العلوم سينكو إيشيغامي ويقرر إعادة بناء الحضارة من الصفر باستخدام قوة العلم، مواجهاً تحديات الطبيعة وصراعات بين الناجين حول شكل العالم الجديد.",
				DescriptionEn: "Suddenly, all of humanity is turned into stone. Thousands of years later, science genius Senku Ishigami awakens and decides to rebuild civilization from scratch using the power of science, facing nature's challenges and conflicts between survivors over the shape of the new world.",
				Seasons:     3,
				Status:      "Running",
				Rating:      8.3,
				Image:       "/uploads/animes/dr-stone.png",
				Cover:       "/uploads/animes/dr-stone.png",
				StudioName:  "TMS Entertainment",
				Duration:    24,
				Language:    "Japan",
				Type:        "TV",
				IsPublished: false,
			},
			epCount: 24,
			cats:    []string{"sci-fi", "adventure", "shounen"},
			year:    2019,
		},
		// 24. Yuri!!! on Ice
		{
			anime: domain.Anime{
				Title:       "Yuri!!! on Ice يوري على الجليد",
				TitleEn:     "Yuri!!! on Ice",
				Slug:        "yuri-on-ice",
				SlugEn:      "yuri-on-ice",
				Description: "بعد هزيمة قاسية، يعود المتزلج يوري كاتسوكي إلى وطنه متردداً في إكمال مسيرته. لكن، بعد ظهور بطل التزلج الروسي فيكتور نيكيفوروف كمدرب له، تبدأ رحلة جديدة وملهمة نحو الجائزة الكبرى، مستكشفة مشاعرهما وشغفهما بالجليد.",
				DescriptionEn: "After a crushing defeat, skater Yuri Katsuki returns to his hometown hesitant to continue his career. However, after Russian skating champion Victor Nikiforov appears as his coach, a new and inspiring journey begins toward the Grand Prix, exploring their feelings and passion for the ice.",
				Seasons:     1,
				Status:      "Completed",
				Rating:      7.9,
				Image:       "/uploads/animes/yuri-on-ice.png",
				Cover:       "/uploads/animes/yuri-on-ice.png",
				StudioName:  "MAPPA",
				Duration:    24,
				Language:    "Japan",
				Type:        "TV",
				IsPublished: false,
			},
			epCount: 12,
			cats:    []string{"sports", "drama", "romance"},
			year:    2016,
		},
		// 25. Lord of the Mysteries
		{
			anime: domain.Anime{
				Title:       "Lord of the Mysteries سيد الألغاز",
				TitleEn:     "Lord of the Mysteries",
				Slug:        "lord-of-the-mysteries",
				SlugEn:      "lord-of-the-mysteries",
				Description: "في عالم يجمع بين الستيم بانك والسحر الفيكتوري، يستيقظ تشو مينغ روي في جسد كلاين موريتي. يكتشف عالماً مليئاً بالبايسي والآلهة والمسارات السحرية. يبدأ رحلته ليصبح 'متجاوزاً' ويسعى لاكتشاف أسرار هذا العالم الغامض والعودة إلى دياره.",
				DescriptionEn: "In a world combining steampunk and Victorian magic, Zhou Mingrui awakens in the body of Klein Moretti. He discovers a world full of Beyonders, gods, and magical pathways. He begins his journey to become a 'Beyonder' and seeks to uncover the secrets of this mysterious world and return home.",
				Seasons:     1,
				Status:      "Upcoming",
				Rating:      9.0,
				Image:       "/uploads/animes/lord-of-the-mysteries.png",
				Cover:       "/uploads/animes/lord-of-the-mysteries.png",
				StudioName:  "Tencent Animation",
				Duration:    24,
				Language:    "China",
				Type:        "ONA",
				IsPublished: false,
			},
			epCount: 12,
			cats:    []string{"action", "adventure", "fantasy", "mystery"},
			year:    2025,
		},
	}

	for _, item := range animes {
		item.anime.ReleaseDate = toDatePtr("2006-01-02", fmt.Sprintf("%d-01-01", item.year))
		descAr := "في هذه الحلقة، نتابع أحداثاً مثيرة ومفصلية في القصة، حيث يتم استعراض تطور الشخصيات والمواجهات التي تشكل مستقبل العالم."
		descEn := "In this episode, we follow exciting and pivotal events in the story, showcasing character development and confrontations that shape the future of the world."
		createAnimeWithEpisodes(db, item.anime, item.epCount, item.cats, item.year, descAr, descEn)
	}
}
